// ═══════════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/sync-web-config.mjs — do not edit by hand.
// Holds deployments made to public chains; merged into deployments.ts.
// ═══════════════════════════════════════════════════════════════════
import type { Deployment, TokenInfo } from "./deployments";

export const GENERATED_DEPLOYMENTS: Record<number, Deployment> =
  {
  "31337": {
    "weth": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
    "factory": "0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512",
    "router": "0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0",
    "merryMenShare": "0xCf7Ed3AccA5a467e9e704C703E8D87F634fB0Fc9",
    "lox": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
    "bowStaking": "0x5FC8d32690cc91D4c39d9d3abcBD16989F875707",
    "feeSplitter": "0x0165878A594ca255338adfa4d48449f69242Eb8F"
  },
  "46630": {
    "weth": "0x1C61880f2F4ce64EaD62a347ECAEA39508b68544",
    "factory": "0x9CbDE27ACEdd5DDd4BC7A152247BeB929C1144F7",
    "router": "0xD76e7a2A8B3c06D62b3F57622a15b9F27945CEA2",
    "merryMenShare": "0xf1553459b978Aa8c9B85b0769dB3b3D8D2AD1356",
    "lox": "0x5355Ca93a24821bc77ee6d19DAF29219328afBc6",
    "bowStaking": "0xb274cf9770D87cb5c1D3DcAc0495D14814EbB809",
    "feeSplitter": "0xf5D72f9639F3ccd5A517D02fab663739E846B708"
  }
} as unknown as Record<number, Deployment>;

export const GENERATED_TOKEN_LISTS: Record<number, TokenInfo[]> =
  {
  "31337": [
    {
      "address": "0x0000000000000000000000000000000000000000",
      "symbol": "ETH",
      "name": "Ether",
      "decimals": 18,
      "isNative": true
    },
    {
      "address": "0x5FbDB2315678afecb367f032d93F642f64180aa3",
      "symbol": "WETH",
      "name": "Wrapped Ether",
      "decimals": 18
    },
    {
      "address": "0xDc64a140Aa3E981100a9becA4E685f962f0cF6C9",
      "symbol": "LOX",
      "name": "Loxley",
      "decimals": 18
    },
    {
      "address": "0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e",
      "symbol": "GOLD",
      "name": "Marian's Gold",
      "decimals": 18
    },
    {
      "address": "0xA51c1fc2f0D1a1b8494Ed1FE312d7C3a78Ed91C0",
      "symbol": "SILV",
      "name": "Sheriff's Silver",
      "decimals": 6
    },
    {
      "address": "0x0DCd1Bf9A1b36cE34237eEaFef220932846BCD82",
      "symbol": "ALE",
      "name": "Friar's Ale",
      "decimals": 18
    }
  ],
  "46630": [
    {
      "address": "0x0000000000000000000000000000000000000000",
      "symbol": "ETH",
      "name": "Ether",
      "decimals": 18,
      "isNative": true
    },
    {
      "address": "0x1C61880f2F4ce64EaD62a347ECAEA39508b68544",
      "symbol": "WETH",
      "name": "Wrapped Ether",
      "decimals": 18
    },
    {
      "address": "0x5355Ca93a24821bc77ee6d19DAF29219328afBc6",
      "symbol": "LOX",
      "name": "Loxley",
      "decimals": 18
    },
    {
      "address": "0xd653EeC375170BE7C320E495132d2F44C2d9Aa17",
      "symbol": "GOLD",
      "name": "Marian's Gold",
      "decimals": 18
    },
    {
      "address": "0xa43776B84b1DF0814795b4AAeD348E8dd47f2F26",
      "symbol": "SILV",
      "name": "Sheriff's Silver",
      "decimals": 6
    },
    {
      "address": "0xA0adB5b3d684e2Da1184866575e0aC4F513803fF",
      "symbol": "ALE",
      "name": "Friar's Ale",
      "decimals": 18
    }
  ]
} as unknown as Record<number, TokenInfo[]>;
