// ═══════════════════════════════════════════════════════════════════
// AUTO-GENERATED by scripts/sync-web-config.mjs — do not edit by hand.
// Holds deployments made to public chains; merged into deployments.ts.
// ═══════════════════════════════════════════════════════════════════
import type { Deployment, TokenInfo } from "./deployments";

export const GENERATED_DEPLOYMENTS: Record<number, Deployment> =
  {
  "46630": {
    "weth": "0x1C61880f2F4ce64EaD62a347ECAEA39508b68544",
    "factory": "0x9CbDE27ACEdd5DDd4BC7A152247BeB929C1144F7",
    "router": "0xD76e7a2A8B3c06D62b3F57622a15b9F27945CEA2",
    "merryMenShare": "0xf1553459b978Aa8c9B85b0769dB3b3D8D2AD1356",
    "lox": "0x5355Ca93a24821bc77ee6d19DAF29219328afBc6",
    "bowStaking": "0xb274cf9770D87cb5c1D3DcAc0495D14814EbB809",
    "feeSplitter": "0xf5D72f9639F3ccd5A517D02fab663739E846B708"
  }
} as unknown as Record<number, Deployment>;

export const GENERATED_TOKEN_LISTS: Record<number, TokenInfo[]> =
  {
  "46630": [
    {
      "address": "0x0000000000000000000000000000000000000000",
      "symbol": "ETH",
      "name": "Ether",
      "decimals": 18,
      "isNative": true
    },
    {
      "address": "0x1C61880f2F4ce64EaD62a347ECAEA39508b68544",
      "symbol": "WETH",
      "name": "Wrapped Ether",
      "decimals": 18
    },
    {
      "address": "0x5355Ca93a24821bc77ee6d19DAF29219328afBc6",
      "symbol": "LOX",
      "name": "Loxley",
      "decimals": 18
    },
    {
      "address": "0xd653EeC375170BE7C320E495132d2F44C2d9Aa17",
      "symbol": "GOLD",
      "name": "Marian's Gold",
      "decimals": 18
    },
    {
      "address": "0xa43776B84b1DF0814795b4AAeD348E8dd47f2F26",
      "symbol": "SILV",
      "name": "Sheriff's Silver",
      "decimals": 6
    },
    {
      "address": "0xA0adB5b3d684e2Da1184866575e0aC4F513803fF",
      "symbol": "ALE",
      "name": "Friar's Ale",
      "decimals": 18
    }
  ]
} as unknown as Record<number, TokenInfo[]>;
